### ISSUE TITLE
Some minor notes on first read-through

### ISSUE THREAD

**Issue by binji** [ISSOtm/gb-asm-tutorial#1]
I made a little checkbox list in case you want to fix these. If you disagree, feel free to just ignore :-)

Index:
- [x] "if you're just a passionate, too". Using "passionate" this way sounds a bit odd to my ear. Maybe "enthusiast" instead?
- [x] "such a small, constrained hardware". "hardware" sounds weird to me. Maybe "device"?
- [x] Personally, I don't really think you need screenshot proof. It sounds a bit defensive.
- [x] You might want to put a link to the repo as a footer on each page. Even better if you can add a link to github issues with a link to that page automatically (I assume that's possible.)

What is Game Boy?
- [x] "These consoles's" looks odd. Maybe "Their successor"?
- [ ] Might be nice to have wikipedia links for the consoles you mention.
- [x] "What is what?" doesn't make sense to me. "What are the differences?" sounds better.
- [x] There are a lot of parentheticals here, which I find a bit hard to read. If it's important, I'd suggest making it part of the sentence proper. If it's just extra information, maybe make it a footnote.
- [x] What does "voluntary wave" mean? Searching finds a bunch of references to gameboy docs, but not much else.

Basic Concepts
- [ ] "non-integers are stored as int1*10^int2" This doesn't really make sense to me. What are int1 and int2 in this example? And what do you mean by non-integers, floating point numbers?
- [x] Might want to mention two's complement in this section.
- [x] "but also one drawback" you mean that you can't tell the difference between code and data? The way you've written it makes it sound like there's something else.

Tools
- [x] Provide links to the emulators!

**Comment by ISSOtm** [comment]
I fixed everything, except three points I'd like to debate.

I have changed the formulation of the screenshot part. I think it sounds less defensive that way.

I'm not sure if wikipedia links to the consoles would be relevant, since they're only cited as a brief history, and described in further detail in the rest of the tutorial (at least how they're programmed on)

I changed the formulation of the part about floating-point numbers, but I'm not sure if it's clearer. What's your opinion?
